title: Zwelithini Tshabalala
description: IT systems, network engineering, cybersecurity and software delivery.
url: https://zw3liy.github.io
baseurl: /Zwelit.github.io
author: Zwelithini Tshabalala
show_downloads: false
plugins:
  - jekyll-seo-tag
